# Usa una imagen de Maven para compilar el proyecto
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Usa una imagen de JDK slim para ejecutar el proyecto
FROM eclipse-temurin:17-jdk as runtime
WORKDIR /app

# Instala curl (opcional para pruebas de conectividad)
RUN apt-get update && apt-get install -y curl

COPY --from=build /app/target/*.jar app.jar

# Expone el puerto de la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]