# Usa una imagen de Java (como openjdk) y construye la aplicación
FROM openjdk:17-jdk
COPY target/springboot-oceanica-0.0.1-SNAPSHOT.jar /app/oceanica-backend.jar
WORKDIR /app
ENTRYPOINT ["java", "-jar", "oceanica-backend.jar"]
