version: '3.9'

services:
  db:
    container_name: oceanica-db
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Infraestructure/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: oceanicadb
      POSTGRES_USER: paula
    ports:
      - "5434:5432"

volumes:
  postgres_data:
